---
- name: Deploy Nginx App
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Apply Deployment
      k8s:
        definition: 'Banking_app_deployment.yml'
        state: present

    - name: Apply Service
      k8s:
        definition: 'service.yml'
        state: present
