---
- name: Deploy Banking App
  hosts: all
  gather_facts: false

  tasks:
    - name: Apply Deployment
      k8s:
        definition: "{{ lookup('file', 'Banking_app_deployment.yaml') }}"
        state: present

    - name: Apply Service
      k8s:
        definition: "{{ lookup('file', 'service.yaml') }}"
        state: present
