---
- name: Deploy Banking App
  hosts: all
  gather_facts: false

  tasks:
    - name: Apply Deployment
      kubernetes.core.k8s:
        definition: 'Banking_app_deployment.yml'
        state: present

    - name: Apply Service
      kubernetes.core.k8s:
        definition: 'service.yml'
        state: present
