- name: Configure Docker on EC2-server Instance created my main.tf
  hosts: all
  become: true
  connection: ssh
  tasks: 
  - name: Updating 
    command: sudo apt update

  - name: Upgrading
    command: sudo apt upgrade -y

  - name: Install Docker
    command: sudo apt-get install docker.io -y
    
  - name: Add user to Docker group
    user:
      name: ubuntu
      append: yes
      groups: docker
      
  - name: Restart docker 
    command: sudo systemctl restart docker     

  - name: Start Docker Service
    command: sudo systemctl start docker

  - name: Run the Bank application
    command: docker run -itd -p 8081:8081 seemayd/banking-app:1.0
